flaskines/app/data/models/gasto.py
from datetime import date
class Gasto:
    def __init__(self, id_gasto:int, fecha: date, descripcion:str, cantidad:int, usuario_id:int):
      self.id_gasto = id_gasto
      self.fecha= fecha
      self.descripcion = descripcion
      self.cantidad = cantidad
      self.usuario_id = usuario_id
   
  

   

flaskines/app/data/models/user.py
class User:
    def __init__(self, id_usuario:int, nombre:str, apellido:str, usuario:str):
      self.id_usuario = id_usuario
      self.nombre = nombre
      self.apellido = apellido
      self.usuario = usuario

   

flaskines/app/app.py
from flask import Flask
from app.utils.db import db
from app.routes.routes import users
app = Flask(__name__)



app.register_blueprint(users)

flaskines/app/routes/routes.py
from flask import Blueprint, render_template, request , redirect, url_for
from app.data.gasto_dao import GastoDao

from app.data.user_dao import UserDao
from app.utils.db import db
from app.data.models.user import User

users = Blueprint("routes", __name__)


@users.route('/')
def home():
    user_dao = UserDao()
    users = user_dao.select_all(db)
    return render_template('index.html',users=users)

@users.route('/new' , methods=['POST'])
def add_user():
    
    nombre=request.form['nombre']
    apellido=request.form['apellido']
    usuario=request.form['usuario']


    if nombre and apellido and usuario:
      cursor = db.cursor() # ESTABLECEMOS UN CURSOR PARA LA CONEXION 
      sql = "INSERT INTO usuarios (nombre,apellido,usuario) VALUES (%s, %s, %s)"
      data = (nombre,apellido ,usuario) # HACEMOS UNA TUPLA CON LOS DATOS 
      cursor.execute(sql,data) # Y SE LO PASAMOS CON LA FUNCION EXECUTE
      db.commit() # ESTO ES PARA MATERIALIZAR LA CONSULTA QUE HEMOS DEFINIDO

    return redirect('/')

@users.route('/edit/<string:id_usuario>', methods=['POST','GET'])
def edit (id_usuario):

    nombre=request.form['nombre']
    apellido=request.form['apellido']
    usuario=request.form['usuario']

    if nombre and apellido and usuario:

       cursor = db.cursor() 
       sql = "UPDATE usuarios SET nombre = %s, apellido = %s, usuario = %s WHERE id_usuario = %s"
       data = (nombre,apellido ,usuario,id_usuario)
       cursor.execute(sql,data) 
       db.commit()
    return redirect(url_for('routes.home'))


@users.route('/delete/<string:id_usuario>')
def delete(id_usuario):
    cursor = db.cursor() 
    sql= "DELETE FROM gastos WHERE usuario_id=%s"
    data = (id_usuario,)
    cursor.execute(sql,data)
    sql = "DELETE FROM usuarios WHERE id_usuario=%s"
    cursor.execute(sql,data)
    db.commit() 
    return redirect(url_for('routes.home')) 



@users.route('/gastos', methods=['POST','GET'])  
def gastos():
    
    gasto_dao = GastoDao()
    gastos = gasto_dao.select_all(db)
    user_dao = UserDao()
    users = user_dao.select_all(db)
    return render_template('gastos.html',gastos=gastos, users=users) 
    
@users.route('/addgastos', methods=['POST','GET'])
def addgastos():
    
    fecha=request.form['fecha']
    descripcion=request.form['descripcion']
    cantidad=request.form['cantidad']
    usuario_id=request.form['usuario_id']


 
    cursor = db.cursor() 
    sql = "INSERT INTO gastos (fecha,descripcion,cantidad,usuario_id) VALUES (%s, %s, %s, %s)"
    data = (fecha, descripcion , cantidad, usuario_id) 
    cursor.execute(sql,data) 
    db.commit()

    return redirect(url_for('routes.gastos'))


@users.route('/deletegastos/<string:id_gasto>')
def deletegastos(id_gasto):
    cursor = db.cursor() 
    sql = "DELETE FROM gastos WHERE id_gasto=%s"
    data = (id_gasto,)
    cursor.execute(sql,data) 
    db.commit() 
    return redirect(url_for('routes.gastos')) 

@users.route('/editgastos/<string:id_gasto>', methods=['GET','POST'])
def editgastos (id_gasto):
    fecha = request.form['fecha']
    descripcion = request.form['descripcion'] 
    cantidad = request.form['cantidad'] 

    if fecha and descripcion and cantidad :
        cursor = db.cursor()
        sql = "UPDATE gastos SET fecha = %s, descripcion = %s, cantidad = %s WHERE id_gasto = %s"
        data = (fecha,descripcion,cantidad,id_gasto)
        cursor.execute(sql,data)
        db.commit()
    return redirect(url_for('routes.gastos')) 

flaskines/app/templates/gastos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gastos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</head>
<body>

    <h1 class="text-center mt-5 mb-5 text-primary">Gastos APPAHORRA</h1>

    <div class="container">
        <div class="card shadow">
            <div class="card-body">
                <form action="/addgastos" method="POST"> <!-- PONEMOS /USER QUE ES DONDE VAN LOS DATOS QUE METAMOS-->
                    <div class="row mb-3">
                        <div class="col">
                            <label>id_usuario</label>
                            <select name="usuario_id">
                                {% for user in users %}
                                <option value="{{user.id_usuario}}">{{user.usuario}}</option>
                                {% endfor %}
                            </select>
                        </div>
    
                        <div class="col">
                            <label>Fecha</label>
                            <input type="date" class="form-control mb-3" name="fecha">
                        </div>
                        <div class="col">
                            <label>Descripcion</label>
                            <input type="text" class="form-control mb-3" name="descripcion">
                        </div>
                        <div class="col">
                            <label>Cantidad</label>
                            <input type="text" class="form-control mb-3" name="cantidad">
                        </div>
                
                        <div class="col">
                            <button class="btn btn-primary mb-3 mt-4" type="submit">Guardar</button>
                        </div>
                        


                    </div>

                </form>

                <!-- TABLA  -->

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            
                            <th scope="col">IdGastos</th>
                            <th scope="col">Fecha</th>
                            <th scope="col">Descripcion</th>
                            <th scope="col">Cantidad</th>
                            <th scope="col">usuario_id</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Eliminar</th>
                        </tr>
                    </thead>
                
                <tbody>
                    {% for gasto in gastos %} <!-- ESTE BUCLE SIRVE PARA ENVIAR LOS DATOS . POR CADA UNO DE LOS ELEMENTOS DE DATA LO VAMOS A IR IMPRIMIENDO DENTRO DE DATA-->
                        <tr>
                           <!-- LAS DOBLES LLAVES ES PARA ACCEDER A LOS DATOS. CON EL '.' ACCEDEMOS AL DATO EN CONCRETO -->
                     
                            <td>{{gasto.id_gasto}}</td>
                            <td>{{gasto.fecha}}</td>
                            <td>{{gasto.descripcion}}</td>
                            <td>{{gasto.cantidad}}</td>
                            <td>{{gasto.usuario_id}}</td>
                            <td><button class="btn btn-primary btn-sm" id="btn-edit{{gasto.id_gasto}}" data-bs-toggle="modal" data-bs-target="#modal{{gasto.id_gasto}}">Edit</button></td>
                            <td><a href="{{url_for('routes.deletegastos',id_gasto=gasto.id_gasto)}}" class="btn btn-danger btn-sm">Delete</a></td>
                      

                       
                        </tr>
                <!-- PARA CERRAR EL BUCLE -->

                        <!-- modal -->
                        <div class="modal fade" id="modal{{gasto.id_gasto}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h1 class="modal-title fs-5" id="exampleModalLabel">{{gasto.id_gasto}}</h1>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="/editgastos/{{gasto.id_gasto}}" method="post">
                                        <label>Fecha</label>
                                        <input type="date" class="form-control mb-3" name="fecha" value="{{gasto.fecha}}">
                                        <label>Descripcion</label>
                                        <input type="text" class="form-control mb-3" name="descripcion" value="{{gasto.descripcion}}">
                                        <label>Cantidad</label>
                                        <input type="text" class="form-control mb-3" name="cantidad" value="{{gasto.cantidad}}">
                                       
                                </div>
                                <div class="modal-footer">
                                  <button type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                                </form>
                              </div>
                            </div>
                          </div>


                    {% endfor %}




                </tbody>

            </table>


            </div>
        </div>
    </div>
    <td><a href="{{url_for('routes.home')}}">Informacion User</a></td>
</body>
</html>

flaskines/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>APPAHORRA</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</head>
<body>

    <h1 class="text-center mt-5 mb-5 text-primary">Base de datos Gastos y Ahorro APPAHORRA</h1>

    <div class="container">
        <div class="card shadow">
            <div class="card-body">
                <form action="/new" method="POST"> <!-- PONEMOS /new QUE ES DONDE VAN LOS DATOS QUE METAMOS-->
                    <div class="row mb-3">
                        <div class="col">
                            <label>Nombre</label>
                            <input type="text" class="form-control mb-3" name="nombre">
                        </div>
                        <div class="col">
                            <label>Apellido</label>
                            <input type="text" class="form-control mb-3" name="apellido">
                        </div>
                        <div class="col">
                            <label>Usuario</label>
                            <input type="text" class="form-control mb-3" name="usuario">
                        </div>
                        <div class="col">
                            <button class="btn btn-primary mb-3 mt-4" type="submit">Guardar</button>
                        </div>
                    </div>

                </form>


                <!-- TABLA  -->

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">ID usuario</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Apellido</th>
                            <th scope="col">Usuario</th>
                            <th scope="col">Editar</th>
                            <th scope="col">Eliminar</th>
                        </tr>
                    </thead>
                
                <tbody>
                    {% for user in users %} <!-- ESTE BUCLE SIRVE PARA ENVIAR LOS DATOS . POR CADA UNO DE LOS ELEMENTOS DE DATA LO VAMOS A IR IMPRIMIENDO DENTRO DE DATA-->
                        <tr>
                            <td>{{user.id_usuario}}</td>  <!-- LAS DOBLES LLAVES ES PARA ACCEDER A LOS DATOS. CON EL '.' ACCEDEMOS AL DATO EN CONCRETO -->
                            <td>{{user.nombre}}</td>
                            <td>{{user.apellido}}</td>
                            <td>{{user.usuario}}</td>
                            <td><button class="btn btn-primary btn-sm" id="btn-edit{{user.id_usuario}}" data-bs-toggle="modal" data-bs-target="#modal{{user.id_usuario}}">Edit</button></td>
                            <td><a href="{{url_for('routes.delete',id_usuario=user.id_usuario)}}" class="btn btn-danger btn-sm">Delete</a></td>
                        </tr>
                <!-- PARA CERRAR EL BUCLE -->

                        <!-- modal -->

                        <div class="modal fade" id="modal{{user.id_usuario}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h1 class="modal-title fs-5" id="exampleModalLabel">{{user.nombre}}</h1>
                                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="/edit/{{user.id_usuario}}" method="post">
                                        <label>nombre</label>
                                        <input type="text" class="form-control mb-3" name="nombre" value="{{user.nombre}}">
                                        <label>apellido</label>
                                        <input type="text" class="form-control mb-3" name="apellido" value="{{user.apellido}}">
                                        <label>usuario</label>
                                        <input type="text" class="form-control mb-3" name="usuario" value="{{user.usuario}}">
                                  
                                </div>
                                <div class="modal-footer">
                                  <button type="submit" class="btn btn-primary">Save changes</button>
                                </div>
                                </form>
                              </div>
                            </div>
                          </div>




                    {% endfor %}

                </tbody>

            </table>


            </div>
        </div>
    </div>

    <td><a href="{{url_for('routes.gastos')}}">Gastos</a></td>
</body>
</html>